version: "3.8"

services:

  db:
    container_name: communis_postgres_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  pgadmin:
    container_name: communis_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head" && uvicorn server:app --host 0.0.0.0 --port ${PORT} --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
